# Generated by Django 2.2 on 2024-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_changepassword_changepasswordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pair',
            field=models.CharField(default='USD', max_length=50),
        ),
    ]
